### ISSUE TITLE
🚀 Dropper csv de sample sur issue (et kickoff datascience) 🚀

### ISSUE THREAD

**Issue by adriens** [opt-nc/domaine-nc-jupyter-notebook#1]
Le csv montré hier en SCRUM

**Comment by adriens** [comment]
Esniute ton te filera le code pour que tu puisses le générer toi -même :+1:

**Comment by spencer-forrest-opt** [comment]
> Le csv montré hier en SCRUM

Committed csv file with '.nc' domaines:
- https://github.com/opt-nc/domaine-nc-jupyter-notebook/commit/c7563aae5987b72004167f981d44b58637e58d52

___Note:___ I will update the file by adding '.asso.nc' and '.nom.nc' domaines when the API and SDK are ready.

**Comment by adriens** [comment]
A toi de jouer @olivierruineau ... ptet bouger le fichier sous `~/data/` ou un truc du genre pour garder une repo propre au niveau 0.

**Comment by spencer-forrest-opt** [comment]
> > Le csv montré hier en SCRUM
> 
> Committed csv file with '.nc' domaines:
> 
> * [c7563aa](https://github.com/opt-nc/domaine-nc-jupyter-notebook/commit/c7563aae5987b72004167f981d44b58637e58d52)
> 
> _**Note:**_ I will update the file by adding '.asso.nc' and '.nom.nc' domaines when the API and SDK are ready.

Committed csv file with '.nc', '.asso.nc' and '.nom.nc' domaines:
- https://github.com/opt-nc/domaine-nc-jupyter-notebook/commit/410c2de1371b79f52147e320a45b524909930e2c

___Note:___ I will update the file by adding protected domaines when the API and SDK are ready.

**Comment by adriens** [comment]
C'est pas une gaussienne !!!

![image](https://user-images.githubusercontent.com/5235127/180373175-97b609cc-dddc-4138-b4af-dd203a484aad.png)

**Comment by adriens** [comment]
y'aurit moyen de fait un piechart sur les providers ? genre certains sont sur aws `awsdns` : 

![image](https://user-images.githubusercontent.com/5235127/180373502-41fae5f6-1dcb-4180-9108-18c7f1043176.png)

et d'autres sur google `.googledomains.com` : 

![image](https://user-images.githubusercontent.com/5235127/180373579-3b43a887-0d9f-4f05-9991-af736f83fc45.png)
