### ISSUE TITLE
:repeat:  Refresh de csv/domaine-nc.csv

### ISSUE THREAD

**Issue by adriens** [opt-nc/domaine-nc-jupyter-notebook#12]
Mettre à jour, j'ai quelques idées...

**Comment by spencer-forrest-opt** [comment]
Waiting on:
 - https://github.com/opt-nc/domaine-nc-jupyter-notebook/pull/13
 
 File updated on that branch 03rd of February 2023

**Comment by adriens** [comment]
yes :heavy_heart_exclamation:

**Comment by adriens** [comment]
@spencer-forrest-opt  👉 https://www.kaggle.com/datasets/optnouvellecaldonie/domainenc
