### ISSUE TITLE
📊  Reporting domaine-nc

### ISSUE THREAD

**Issue by ThomasJoncourt** [opt-nc/domaine-nc-jupyter-notebook#5]
# ❔ A propos

Reporting sur le jeu de donnée [`domaine-nc`](https://github.com/opt-nc/domaine-nc-jupyter-notebook/blob/main/domaine-nc.csv) pour une présentation rapide (5 minutes) à la CPS

# 🧽 Actions

- [ ] Nettoyage des données
- [ ]  Création de chartes graphiques 
- [ ]  Exportation des graphiques les plus pertinents

# 🔖 Bookmarks

**Comment by ThomasJoncourt** [comment]
![3D_1](https://user-images.githubusercontent.com/101191286/194995167-efc78e45-929a-4e09-b7ea-ba7901aba75f.png)
![bloom-visualisation](https://user-images.githubus
![bloom-visualisation8](https://user-images.githubusercontent.com/101191286/194995198-42a1c927-c348-47dd-80fb-33a58de5174a.png)
ercontent.com/101191286/194995180-375b72ff-f403-4af0-a82a-0fb703abb7b9.png)
![bloom-visualisation4](https://user-images.githubusercontent.com/101191286/194995182-61a70f27-ef6f-4c8f-b3b2-c1360505733c.png)
![bloom-visualisation5](https://user-images.githubusercontent.com/101191286/194995183-bf43fe50-cefe-4637-997b-7e923bfdb5f7.png)
![bloom-visualisation6](https://user-images.githubusercontent.com/101191286/194995186-3018d313-1b8d-4bb5-bfaa-b63f94d57c52.png)
![bloom-visualisation7](https://user-images.githubusercontent.com/101191286/194995187-c63a9f1a-25ac-4b08-ade2-d35394673ed9.png)

**Comment by ThomasJoncourt** [comment]
<img width="353" alt="test" src="https://user-images.githubusercontent.com/101191286/194998784-8fabc069-b2c4-416d-94f4-bff3fc049657.png">
![gephi_all_nodes_forceatlas2](https://user-images.githubusercontent.com/101191286/194998788-4c5147b6-779a-4f79-8612-a7aeaa4a1729.png)
![gephi_all_nodes_OpenOrd](https://user-images.githubusercontent.com/101191286/194998790-e0ef113e-d92d-4d7b-8dd9-bd631f4925d3.png)
<img width="317" alt="gephi_clipboard" src="https://user-images.githubusercontent.com/101191286/194998792-bafcdf7b-dc8e-437a-84f3-663c8c17d40d.png">
![gephi_viz_sans_lien](https://user-images.githubusercontent.com/101191286/194998795-cbc11d54-6f53-4ff9-895e-e3b06020eb86.png)

**Comment by ThomasJoncourt** [comment]
![gephi_all_nodes_forceatlas2](https://user-images.githubusercontent.com/101191286/194998864-8e1dc327-c57f-47bf-9304-be940ce4f264.png)
![gephi_all_nodes_OpenOrd](https://user-images.githubusercontent.com/101191286/194998867-39aa3d4f-4964-4bc2-8f82-e0b42b4a3c38.png)
<img width="317" alt="gephi_clipboard" src="https://user-images.githubusercontent.com/101191286/194998869-88c95bbe-73c4-479c-8bb0-0416e6eaf8a9.png">
![gephi_viz_sans_lien](https://user-images.githubusercontent.com/101191286/194998870-9ddb3c6a-8418-401b-a194-fb66468f11b8.png)
<img width="353" alt="test" src="https://user-images.githubusercontent.com/101191286/194998873-81338fe4-b7a6-42db-b531-72315a6f2444.png">

**Comment by ThomasJoncourt** [comment]
![newplot](https://user-images.githubusercontent.com/101191286/194999884-4c920833-23cc-46f2-9f59-0756e59f228c.png)
![newplot2](https://user-images.githubusercontent.com/101191286/194999889-edd4d76c-147c-487a-b6e0-385a0385a6a0.png)
![newplot3](https://user-images.githubusercontent.com/101191286/194999891-5d6f1c76-64f5-4b90-b694-ef4df0d4f7d6.png)
![newplot4](https://user-images.githubusercontent.com/101191286/194999894-1996d59d-26c6-4774-a725-4b9e4e634f57.png)

**Comment by ThomasJoncourt** [comment]
![evolution_nombre_site](https://user-images.githubusercontent.com/101191286/195233729-989635a9-1398-4e42-a608-e22fd47f7a87.png)
![part_marche_gestionnaire](https://user-images.githubusercontent.com/101191286/195237079-69beffc1-17b8-401f-bd1e-281673987245.png)
![part_marche_dns](https://user-images.githubusercontent.com/101191286/195237085-2d7f6290-8f27-4fd8-aaf4-d294eb769ad1.png)
![date_expiration](https://user-images.githubusercontent.com/101191286/195237123-87fb9731-7afd-4acc-b3d4-7b561ba431e2.png)

**Comment by ThomasJoncourt** [comment]
![count_year_black](https://user-images.githubusercontent.com/101191286/195251204-2143edf0-61af-4182-a2d6-f7d7c103a588.png)
![count_year](https://user-images.githubusercontent.com/101191286/195251218-619c4dfb-e74e-4240-8642-239071e63462.png)

**Comment by adriens** [comment]
Super @ThomasJoncourt , y'a u nsuper matos là !

👉 Tu pourrais, sur la dernière vesion du csv, faire un top sur ceux qui ont le plus de dns car  @spencer-forrest-opt  a ajouté de la très belle data et et même découvert des gars avec 6 dns !!!

**Comment by adriens** [comment]
je te poserai quelques questions demain sur certains vis obtenus via Gephi

**Comment by adriens** [comment]
Où est le chart avec les gauges que tu 'mavais montré @ThomasJoncourt ?

**Comment by adriens** [comment]
@ThomasJoncourt  : [monter la résolution des exports images cf tuto](https://youtu.be/5xju0b2ETLk?t=66) .... afin de disposer de meilleure qualité :pray:

**Comment by ThomasJoncourt** [comment]
<img width="864" alt="reg_poly" src="https://user-images.githubusercontent.com/101191286/195470908-2157ce67-912a-4ceb-9997-dfec61123205.png">

![box](https://user-images.githubusercontent.com/101191286/195471243-09674d42-4529-4632-8c26-5e335e50afdb.png)

**Comment by ThomasJoncourt** [comment]
## Commentaire : Sur les 18 sites web ayants expirés dans notre jeu de données : 13 n'avaient pas de gestionnaires, 3 sont gérés par "LA FABRIK" et ont expirés le jour de la récupération du fichier csv (Une coupure non prévu ?),1 site géré par "NAUTILE" et 1 site géré par "ENGIE PACIFIQUE INFORMATIQUE" expiré la veille de la récupération des informations.

**Comment by ThomasJoncourt** [comment]
![dns_sup_3](https://user-images.githubusercontent.com/101191286/195502602-01b8fb54-167c-4ec5-834b-3d398200d5a0.png)

**Comment by ThomasJoncourt** [comment]
COMMENTAIRE: 2 serveur DNS minimum pour tout les sites, 3 dns mini pour 38,68% des sites et le reste voir sur graphique précédant

**Comment by adriens** [comment]
https://heavenfactory.com/home 💪

**Comment by adriens** [comment]
Merci @ThomasJoncourt : good job 👍

**Comment by adriens** [comment]
Rdv demain 🚀
