### ISSUE TITLE
Générer le nouveau fichier avec plus de 3 dns

### ISSUE THREAD

**Issue by adriens** [opt-nc/domaine-nc-jupyter-notebook#7]

**Comment by spencer-forrest-opt** [comment]
Updated CSV file:
- https://github.com/opt-nc/domaine-nc-jupyter-notebook/commit/527f62f621af7a306a8f15493032b085b4c2f3b1

Max count of DNS found with the generated file is 6:

- [118.nc](https://www.domaine.nc/whos?domain=118&ext=.nc)
- [afk.nc](https://www.domaine.nc/whos?domain=afk&ext=.nc)
- [artia.nc](https://www.domaine.nc/whos?domain=artia&ext=.nc)
- etc...

**Comment by adriens** [comment]
> Max count of DNS found with the generated file is 6:

😮 ❕ 

@ThomasJoncourt , ce nouveau fichier pète-t-il tes intégrartions neo4J et Jupyter ?
