### ISSUE TITLE
:art:  GraphXR datavis > pour de l'art :artist: 

### ISSUE THREAD

**Issue by adriens** [opt-nc/domaine-nc-jupyter-notebook#8]
:warning:  Pour ce matin du 13/10/2022 : 

- [x] Produire une très belle image des données via Neo4J
- [x] Produire une version video mettant en valeur la structure 3d des données

**Comment by adriens** [comment]
A toi de jouer @pluaki :rocket:

**Comment by pluaki** [comment]
Remarque sur mise en place dans neo4j, du projet `DomaineNC` :
- mettre à jour la version DBMS pour créer la BDD sans erreur sur Neo4j
👉 la version utilisée sur neo4j de mon PC : 4.3.1 
👉 passage à la version 4.4.5
- création de la base dans neo4j pour DomaineNC à partir du fichier `.dump`

vu avec @ThomasJoncourt

**Comment by pluaki** [comment]
Ensemble des données `DomaineNC`
`MATCH (n)-[r]-(m) RETURN n,r,m;`

Zoom
![image](https://user-images.githubusercontent.com/62574957/195479928-65184a28-960b-4d5a-92ef-37816c5440cd.png)

![image](https://user-images.githubusercontent.com/62574957/195480101-0bcbf6f6-99f1-43e6-89de-eb121a925d9b.png)

Rotation
![image](https://user-images.githubusercontent.com/62574957/195480391-0d2b1cef-cabe-4b98-bf10-e20dc7739d3a.png)

![image](https://user-images.githubusercontent.com/62574957/195480552-a5ab6a9a-0bc0-4e16-ac75-4dc7180eb5c0.png)

![image](https://user-images.githubusercontent.com/62574957/195480663-4cf6292e-989a-4887-8431-99b791dbfa0b.png)

**Comment by adriens** [comment]
Excellent @pluaki , c'est un sacré bon boulot ❣️

**Comment by adriens** [comment]
Hâte de voir les videos 😮

**Comment by pluaki** [comment]
https://user-images.githubusercontent.com/62574957/196058009-280fdd57-fc27-4ec8-a35a-3e5aef5d7598.mp4

**Comment by pluaki** [comment]
quelques exemples : https://community.kineviz.com/c/gallery/12

**Comment by pluaki** [comment]
https://user-images.githubusercontent.com/62574957/196060199-3f709e8e-fa08-4f82-b295-576e4bc6af99.mp4

**Comment by pluaki** [comment]
https://user-images.githubusercontent.com/62574957/196061015-d7098ef0-8150-4bec-a094-b25ebd95ac0d.mp4

**Comment by pluaki** [comment]
bon ben voilà 3 vidéos , c'est quand même mieux au bureau qu'en remote 😆

**Comment by adriens** [comment]
Yes c'est top, je les intègre.

maintenant c'est en mode bonus pur. Si tu sors un truc c'est que du bonus, contrat rempli 👏 👍

**Comment by adriens** [comment]
- https://youtu.be/bLhv7GOuwa8
- https://youtu.be/R6fFjs28PvA
- https://youtu.be/Ke7ioOPAlz0

**Comment by pluaki** [comment]
voilà une autre vidéo : elle est un peu moins saccadée que la 1ère - finalement, c'est plus fluide quand c'est en direct 😄 

https://user-images.githubusercontent.com/62574957/196066385-fc9c1efa-5dbd-4323-8c3b-362a1539f895.mp4

**Comment by adriens** [comment]
YEs, beaucoup plus smooth 👍 

https://youtu.be/AqOE42GF1HI
